### ISSUE TITLE
:bug: querying with expired tokens return 500 errors

### ISSUE THREAD

**Issue by bunop** [cnr-ibba/SMARTER-backend#14]
- [x] Deal with expired tokens
- [x] Return a more user friendly error message

**Comment by bunop** [comment]
```
uwsgi_1  | Traceback (most recent call last):
uwsgi_1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
uwsgi_1  |     rv = self.dispatch_request()
uwsgi_1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
uwsgi_1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
uwsgi_1  |   File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
uwsgi_1  |     resp = resource(*args, **kwargs)
uwsgi_1  |   File "/usr/local/lib/python3.9/site-packages/flask/views.py", line 83, in view
uwsgi_1  |     return self.dispatch_request(*args, **kwargs)
uwsgi_1  |   File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
uwsgi_1  |     resp = meth(*args, **kwargs)
uwsgi_1  |   File "/usr/local/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 120, in decorator
uwsgi_1  |     verify_jwt_in_request(optional, fresh, refresh, locations)
uwsgi_1  |   File "/usr/local/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 68, in verify_jwt_in_request
uwsgi_1  |     jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
uwsgi_1  |   File "/usr/local/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 286, in _decode_jwt_from_request
uwsgi_1  |     decoded_token = decode_token(encoded_token, csrf_token)
uwsgi_1  |   File "/usr/local/lib/python3.9/site-packages/flask_jwt_extended/utils.py", line 122, in decode_token
uwsgi_1  |     return jwt_manager._decode_jwt_from_config(encoded_token, csrf_value, allow_expired)
uwsgi_1  |   File "/usr/local/lib/python3.9/site-packages/flask_jwt_extended/jwt_manager.py", line 536, in _decode_jwt_from_config
uwsgi_1  |     return _decode_jwt(**kwargs, allow_expired=allow_expired)
uwsgi_1  |   File "/usr/local/lib/python3.9/site-packages/flask_jwt_extended/tokens.py", line 87, in _decode_jwt
uwsgi_1  |     decoded_token = jwt.decode(
uwsgi_1  |   File "/usr/local/lib/python3.9/site-packages/jwt/api_jwt.py", line 119, in decode
uwsgi_1  |     decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
uwsgi_1  |   File "/usr/local/lib/python3.9/site-packages/jwt/api_jwt.py", line 106, in decode_complete
uwsgi_1  |     self._validate_claims(payload, merged_options, **kwargs)
uwsgi_1  |   File "/usr/local/lib/python3.9/site-packages/jwt/api_jwt.py", line 142, in _validate_claims
uwsgi_1  |     self._validate_exp(payload, now, leeway)
uwsgi_1  |   File "/usr/local/lib/python3.9/site-packages/jwt/api_jwt.py", line 177, in _validate_exp
uwsgi_1  |     raise ExpiredSignatureError("Signature has expired")
uwsgi_1  | jwt.exceptions.ExpiredSignatureError: Signature has expired
```
